### ISSUE TITLE
Change path of docker-compose command

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#1]
The mvn commands needs to be run in the root of the project directory.  Your README.md file provides this command to execute:

`mvn clean package docker:build`

If the assumption is that commands will be run from the root directory, please consider changing the docker compose command from:

`docker-compose -f common/docker-compose.yml up`

to:

`docker-compose -f docker-compose/common/docker-compose.yml up`

as I believe this is what it should be from the root directory.

**Comment by carnellj** [comment]
Done

**Comment by joshuawhite929** [comment]
John, 

Did you push your changes?  I don't see the change reflected in the README.md file.

-Joshua

https://github.com/carnellj/spmia-chapter1

**Comment by carnellj** [comment]
Yes.  Everything should be pushed
