### ISSUE TITLE
Reference contains code that is different than listing 1.2

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#10]
Right after listing 1.2, you make two different references to the code.  The second reference (starting with "ResponseEntity<String>" uses the following path:

http://**logical-serviceid**/name/{firstName}/{lastName}

This is different from what is in code listing 1.2.  I believe this was meant to align with cue ball #4 in listing 1.2.

**Comment by carnellj** [comment]
Cleaned up and made this consistent. Also modified the text to explicitly let the reader know that the code is not in chapter 1.
