### ISSUE TITLE
Chapter 1 & 2 have inconsistent directory structure

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#11]
John,

The directory structures for chapters 1 & 2 are slightly different than those used for the rest of the book.  The text that you have outlined in section 1.3 and 1.4 of Appendix A may be confusing as a result.  This may/may not be an issue for you.  As an example:

1.  The path to the docker-compose file in chapters 1 & 2 is docker-compose/common/docker-compose.yml vs. docker/common/docker-compose.yml in the rest of the book.  Chapters 1 & 2 don't align with the example path your provide in section 1.6 of Appendix A.
2.  Chapters 1 & 2 aren't organized in the "service" layout/structure that is used in the rest of the book.   If you wanted to make Chapters 1 & 2 more like the rest of the book, you could wrap the existing source into a "simpleservice" service folder (just an example).

**Comment by carnellj** [comment]
Refactored the code to change the docker directory and also changed to include a service directory.  Need to double check chapter2
