### ISSUE TITLE
Fix URL

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#119]
Please swap the IP for localhost:

`http://192.168.99.100:5555/api/licensing/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/f3831f8c-c338-4ebe-a82a-e2fc1d1ff78a`

change to:

`http://localhost:5555/api/licensing/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/f3831f8c-c338-4ebe-a82a-e2fc1d1ff78a`

**Comment by carnellj** [comment]
Fixed
