### ISSUE TITLE
docker-compose command missing "up" command

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#12]
Before and after Figure A.2, the sample docker-compose commands are missing the "up" command.  This is also true for the very last line of Appendix A. For example, you have:

`docker-compose -f docker/common/docker-compose.yml`

when you probably meant:

`docker-compose -f docker/common/docker-compose.yml up`

**Comment by carnellj** [comment]
oops fixed and reloaded into the box right away
