### ISSUE TITLE
Chapter 7 Typos and Wording Problems

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#121]
"involves multiple layers of **protections**, including: "

"defined ports and **accessible a small** number of authorized servers"

"themselves with a third-party **authentications** service. "

"be validated back to the **authentications** service"

"The main goal behind OAuth2 is services that are called by a user can" - Wording?

"The real power behind OAuth2 is that allow application " - Wording?

"application as the only application with our OAuth2" - Wording?

"I am using access here **is** the broad term"

"for application information: **a** in-memory store "

"**is a passed a** comma-separated list of "

"when they ask for a key **they need define** "

"network be able to access the same data" - Wording?

"handle user information that will be returned by **the** Spring"

"Figure 7.4 shows the JSON payload that is **return** from"

"In figure 7.5 we are issuing **an** HTTP GET"

"The first thing we are going to do **is a protect** "

"organization **service that it can** only "

"we will get 401 HTTP response" - missing "a"

"indicating that **the full authentication**"

"make a call **to licensing REST** endpoint"

"The services gateway will need copy the"

"As part of its work the licensing service, has " - Verify comma position(s)

"These means that there is no need" - Probably meant "This"

"JWT token and **exposes** its content"

"This is a trivial exercise that involves **requires** you to do two things"

"To do the enhancement we need to **add override the**"

"HashMap and the set on the"

"configure() method **pf** the JWTOAuth2Config"

"**system.out.println** to the run() " - Capitalization

"HTTPs" - Capitalization - there are several of these...

"Zuul allows you be consistent in how"

"To this separate, start with separating " - Wording?

"eagle eye" - perhaps do a find and replace.  It looks like it should be EagleEye

"application data should at the least be in "

"by microservices services residing "

"I tend to take a most paranoid view" - Wording?

"and also is an increase in overall complexity" - Wording?

"How locked down should be the private API zone be" - Wording?

"have open in order for their service functions" - Wording?

**Comment by carnellj** [comment]
Fixed
