### ISSUE TITLE
Section 1.2.4 - basic authentication call doesn't work

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#129]
John,

In the beginning of section 1.2.4, you have a url specified:

`http://192.168.99.100:8901/auth/oauth/token `

This should be changed to use localhost:

`http://localhost:8901/auth/oauth/token`

Beyond this issue though, the paragraph seems to indicate that running the example in figure 7.2 will work.  It does not.  As expected, the authentication service complains that you need to specify a grant_type etc.  This is covered in Figure 7.3 (which works).

Was this example supposed to work?  If so, what state does the code need to be in to make it work?

**Comment by carnellj** [comment]
fixed.  Never was able to reproduce the problem you were describing, but I put some clarifying text in the chapter to let the reader know that after setting the basic auth keys they were not ready to continue until they setup the HTT form parameters.
