### ISSUE TITLE
Alternative to approach in "Tip" section following Figure A.2

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#13]
While you can use `grep` to achieve this, you can achieve the same by executing the following docker-compose command:

`docker-compose -f docker/common/docker-compose.yml logs -f licensingservice`

after your services are launched with:

`docker-compose -f docker/common/docker-compose.yml up`

or launching in detached mode with:

`docker-compose -f docker/common/docker-compose.yml up -d`

**Comment by carnellj** [comment]
Thats funny you brought up because I actually looked at the logs that way in Chapter 10. 

 docker-compose -f docker/common/docker-compose.yml logs -f licensingservice

I even make small note of it in Chapter 10.

I probably was drinking too much cough syrup when I wrote the appendix :-)
