### ISSUE TITLE
Fix paths - two paragraphs right before Figure 7.5

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#134]
In the two paragraphs before Figure 7.5, you mention the path `/users` three separate times.  I suspect that you are trying to refer to the URL that is shown in Figure 7.5.  If that is the case, it should be `/auth/user` in all three cases

In the two paragraphs after Figure 7.5, you mention the path `/user` (three times).  I suspect you are still referring to the same endpoint and should also be `/auth/user` in both cases

**Comment by carnellj** [comment]
Fixed
