### ISSUE TITLE
Inconsistencies - "EagleEye" vs "Eagle Eye" 

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#14]
Yes, this isn't a technical thing, but may be something the editors have missed.  There are several places where you are swapping between "EagleEye" and "Eagle Eye" and "eagle eye".  While this occurs in Chapter 2, I suspect you may be able to do a find and replace in the other chapters as well.  It looks like "Eagle Eye" is used the most.  Note: this also occurs in the text within the images you use as well.

**Comment by carnellj** [comment]
Fixed
