### ISSUE TITLE
Section 1.3.3 - Change ResourceServerConfigurerAdapter -> ResourceServerConfiguration

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#140]
At the beginning of Section 1.3.3 you make a reference to the code in listing 7.5.  This class is `ResourceServerConfiguration` which extends `ResourceServerConfigurerAdapter` .

In the text, you call this class `ResourceServerConfigurerAdapter` incorrectly (see right before the file path)

**Comment by carnellj** [comment]
fixed
