### ISSUE TITLE
Listing 7.6 and text before...

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#142]
John,

Two things:

1.  Can we remind the reader which URL we are testing here so they may be able to test this themselves?  I think the URL might have been (please verify) `http://localhost:8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a`
2.  Can you replace the IP in the figure with localhost?

**Comment by carnellj** [comment]
Fixed
