### ISSUE TITLE
Testing the DELETE option - Code change proposal for the OrganizationServiceController

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#145]
John,

In the Organization controller, you have the following:

```
    @RequestMapping(value="/{organizationId}",method = RequestMethod.DELETE)
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void deleteOrganization( @PathVariable("organizationId") String orgId,  @RequestBody Organization org) {
        orgService.deleteOrg( org );

    }
```

Is it necessary to supply the organizationId as part of the URL and pass the Organization in JSON format for the body?  Can we simplify this and only require the ID in the URL?  That would require a slight code change on your part.  Looking through the documents, its unclear what the recommended guidelines are for the DELETE operation.  I think skipping the body simplifies things.  Also, I am not really sure how to test this.  Can you share how you tested this (in its current form) Thoughts?

FYI - I did test the "as-is" solution.  It works as described.  The only headache was that after deleting the organization, if you tried to read it again, you get a 500 error.  I used httpPie to run the following:

john.carnell
```
http :8901/auth/user 'Authorization:Bearer 2f151f31-de3e-4d14-87e9-33f72709d67b'
http :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer 2f151f31-de3e-4d14-87e9-33f72709d67b'
http --download --output organization.json :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer 2f151f31-de3e-4d14-87e9-33f72709d67b'
http DELETE :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer 2f151f31-de3e-4d14-87e9-33f72709d67b' < organization.json
```

william.woodward
```
http :8901/auth/user 'Authorization:Bearer fd7ee9a3-15db-403a-b2b2-18bd455c9b51'
http :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer fd7ee9a3-15db-403a-b2b2-18bd455c9b51'
http --download --output organization.json :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer fd7ee9a3-15db-403a-b2b2-18bd455c9b51'
http DELETE :8085/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a  'Authorization:Bearer fd7ee9a3-15db-403a-b2b2-18bd455c9b51' < organization.json
```

**Comment by carnellj** [comment]
Actually that was a moment of stupidity.  I have already changed this code in a couple of different spots to only use the URL.
