### ISSUE TITLE
Fix Path(s)

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#153]
You have:

`{licensing-service/organization-service}/src/main/com/thoughtmechanix/xxx/security/JWTTokenStoreConfig.java`

It should be:

`{licensing-service/organization-service}/src/main/java/com/thoughtmechanix/xxx/security/JWTTokenStoreConfig.java`

Really though, it may be more clear just to list the two paths independently:

```
licensing-service/src/main/java/com/thoughtmechanix/licenses/security/JWTTokenStoreConfig.java

organization-service/src/main/java/com/thoughtmechanix/organization/security/JWTTokenStoreConfig.java
```

**Comment by carnellj** [comment]
fixed
