### ISSUE TITLE
Add comment following URL

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#159]
In the text, you have:

`http://localhost:5555/api/licensing/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/f3831f8c-c338-4ebe-a82a-e2fc1d1ff78a`

If the user runs this, it won't work.  Perhaps we can remind them to add the token to this request as well.

**Comment by carnellj** [comment]
fixed
