### ISSUE TITLE
Are you still using https://github.com/carnellj/native_cloud_apps?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#16]
Section 2.3.1 of Chapter 2 has a reference to https://github.com/carnellj/native_cloud_apps.  Is this something that you are still using or should this be replace with a reference to the chapter 2 code (https://github.com/carnellj/spmia-chapter2)?

The contents of the README.md file seem to be stale as it doesn't reflect the rest of the chapters.  In addition, the contents seems to overlap with what is now in appendix A.  Thoughts?

**Comment by carnellj** [comment]
Fixed
