### ISSUE TITLE
Appendix B Typos/Wording Issues

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#160]
Search for the following:

"users have come to **be** expect that"

"explicitly trust **on** another"

"authenticate **again** the EagleEye OAuth2 service"

"uniquely identifies the application trying to access the any protected resources" - wording

"The **different** between"

"between the password grant and the client credential **grants** is" - should grant be singular?

"by only using the **register** application name "

"provided return back an OAuth2 access token" - wording

"and access their **Eagle** Data via the organization service" - EagleEye?

"incoming request and **run a JavaScript** " - wording

"Keep several things to keep in mind" - wording

"token for in your behalf" - wording

"The next time the user **tries calls** a service"

"The organizations will try to validate the token" - Organization Service?

"JSON payload **indicating that indicating that** the token"

"you have a service-to-**services** interaction" - singular?

**Comment by carnellj** [comment]
Fixed
