### ISSUE TITLE
Chapter 8 Typos/Wording/Comma Placement issues

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#161]
Search for the following text:

"you’re doing because you can now answer **to** the age"

"The reality is that human beings are constantly in a state of motion, interacting with their environment around them, while sending out and receiving information." - Wording...

"As we receive messages we react to those" - comma after messages?

"to communicate with other **microservice** using asynchronous"

"It also known as a message driven architecture" - wording

"tightly coupled to specific libraries or **service**" - plural?

"how to build a caching solution simple architecture" - wording

"In a synchronous request-response model changes into state data" - comma after model, also wording

"it will call the **organization’s** service " - just "organization" service?

"deletes the organization record using the **organization’s** REST " - consider replacing "organization's" with "organization service's"

"needs an endpoint on the licensing service exposed that the organization service call" - wording

"Having the organization service talk to **redis**" - capitalize Redis

"This means we can easily add new **messages** consumers" - singular

"It is also means if you are using messages " - wording

"If a message fails do you retry" - missing comma after fails?

"where the user transactions can be executed in **different orders**" - consider replacing with "out of order"

"Since had the servers communicate" - wording

"file recovery server into event stream " - missing "an"?

"messaging based platform before the new terminology " - missing comma after "before"?

"Spring Cloud Stream fits is used" - wording

"A source is a Spring annotated **interfaces**" - singular

"A source takes the message serializes" - wording

"allows you to work with message and consumers" - consider replacing "message and consumers" with just "messages"

"basic components in a Spring Cloud Stream" - wording

"with the message in the licensing **services**" - singular?

"We are going to begin by **modify**" - "modifying"?

"every time organization data is added or deleted" - should include "updated" as well

"This **publish** message will include " - published?

"The first thing **we need to is set up** " missing "do"?

"set up our maven dependencies" - capitalize Maven

"dependencies **in organization** service’s" - missing "the"

"organization service’s maven" - capitalize Maven

"Once the maven dependencies " - capitalize Maven

"the organization-service’s" - remove the hyphen.  While valid, its not consistent with how you have referenced this service in the text

"The use of Source.class in the **@EnableBindings**" - should be @EnableBinding

"Remember, channel sets" - sits?

"Now let’s, go ahead" - consider moving the comma after "Now"

"#B  The message to be published is a java POJO" - capitalize Java

"service only needs to publish to single " - missing "a"

"However, at this point everything " - consider comma after "point"

"service’s Spring Cloud Stream source" - capitalize Source

"#A stream.bindings is the start of our mapping our service" - wording

"channel and maps to Source.output() channel " - wording

"gives a hint to **the** Spring Cloud Stream" - remove "the"?

"stream.bindings.kafka property tells spring" - Capitalize Spring

"the network location of our Kafka and Zookeeper" - wording

"property spring.stream.bindings.kafka property" - wording

"#A Spring autowiring is **use** to inject" - used

"There is still is a chance " - wording

"**@EnableBindings** annotation. The difference" - should be "@EnableBinding"

"@EnableBinding annotation tells the service **to listen to the use** " - wording

"the Sink Interface’s to listen" - wording

"going to pass the @EnableBindings annotation" - should be "@EnableBinding"

"stream will automatically **serialize** the message" - should this be deserialize?

"one copy of the **service** will be consumed" - message?

"added, updated, or deleted, and the" - remove comma after deleted

"Using Redis as a **distribute** cache " - distributed

"With my current employer we build " - comma after employer?

"we have seen significant **improvements performance** by " - swap words?

"Fortunately, the Spring project, Spring Data, already " - wording

"The first thing we need to do in include the Spring Data for Redis " - wording

"Redis is a key-value store data store that acts like big distributed, in-memory Hashmap" - wording?

"mechanism **to use Java class to** access " - wording

"#A  The @Repository **interface** tells Spring " - annotation?

"This means in every operation " - missing that?

"Trying to retrieve an Organization class with **is** organization Id " - it's

"Want to log the exception and return null " - wording

"we **save** the returned organization object " - use "cached" instead of save?

"we hit the licensing service get endpoint a second time" - remove "get"?

"customize the names of your channels you can define" - comma after channels?

"define your own interface and expose as many inputs and output" - "inputs" should be "input"

"To use a custom channel **inboundOrgChange** licensing service" - should be "inboundOrgChanges"

"In the case of an output channel, you the defined method" - wording

**Comment by carnellj** [comment]
Fixed
