### ISSUE TITLE
Consider listing the JSON that the reader can use for the POST discussed in section 8.3.3

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#166]
John,

In section 8.3.3, you provide the URL for the reader to execute a POST operation to test the source, but don't provide the JSON that needs to get posted.  Can you consider adding this?

I believe its supposed to be like this:

```
{
    "contactEmail": "mark.balster@custcrmco.com",
    "contactName": "Mark Balster",
    "contactPhone": "823-555-2222",
    "id": "e254f8c-c442-4ebe-a82a-e2fc1d1ff78a",
    "name": "customer-crm-co"
}
```

**Comment by carnellj** [comment]
Done
