### ISSUE TITLE
Additional callout on Message versioning?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#169]
Take or leave this one...

The rest of the book deals with HTTP based REST services which generally have an approach for dealing with versioning changes (in the URL) and provides a mechanism to accommodate contract changes as a result.

In chapter 8, you talk about Messaging, and have services serializing messages directly into POJOs.  While messaging adds a layer of indirection between services, based on the current approach, a change to the Message that the organization service sends will break the licensing service and any other service that consumers those messages (tight coupling again).  Is this something worthwhile to point out or warn the reader about?

**Comment by carnellj** [comment]
done
