### ISSUE TITLE
Directory structure out of sync

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#17]
This is a simple one..  In the text, right before Listing 2.1, you ask the reader to either pull down the source code (see also issue #16) or create a project with the following structure.

The project you have in git doesn't have the following packages (as there is no source for them):

- config
- repository
- resources

You can simply remove these references from the bulleted list immediately before Listing 2.1.

**Comment by carnellj** [comment]
fixed
