### ISSUE TITLE
Refactor com.thoughtmechanix.organization.event package to be com.thoughtmechanix.organization.events

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#175]
John,

I don't know if this is intentional or not, but you have two similarly named packages in the organization-service:

- `com.thoughtmechanix.organization.event`

- `com.thoughtmechanix.organization.events`

Based on the fact that the `com.thoughtmechanix.organization.events` package exists in the licensing-service as well, I suspect that "events" is right.

IMPACTS:

If you decide to refactor this, you will need to update the references to the class com.thoughtmechanix.organization.event.models.OrganizationChangeModel in the text.

**Comment by carnellj** [comment]
Fixed
