### ISSUE TITLE
Listing 2.1 pom.xml out of sync

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#18]
The Maven pom in listing 2.1 needs to be updated to reflect the you are now using the 1.4.4.RELEASE version of the spring-boot-starter-parent.

Overall, the code listing is incomplete as it is missing the "properties" section and the rest of the plugins.  In addition, it looks like you have a plugin listed twice?  Perhaps you could simply grab the latest from the source to get the code listing in sync?

FYI - the text makes reference to the fact that you have a comment in Listing 2.1 indicating that you did not include the Spotify Docker plugin in the code listing.  This comment doesn't appear to be in this code listing now.  Please add it back in when you sync this up.

**Comment by carnellj** [comment]
fixed
