### ISSUE TITLE
Chapter 9 Typos, Wording and Comma Issues

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#184]
Search for the following:

"Querying using **a** log aggregation **tools**" - wording

"Zipkin allows you break a transaction down" - wording

"component pieces and then **visual** identify"

"To being this chapter we start with the simplest of tracing tools" - wording

"correlation ID directly to **Spring’s MDC** (Mapped Diagnostic Context)" - technically, this is a SLF4J thing, not a Spring thing.  Is this worth changing?

"Add the correlation information to **Spring’s MDC**" - same as above

"Add Spring Cloud Sleuth tracing information to the Spring MDC" - same as above

"integrate to Zipkin to visualize our transactions" - wording

"Since every query might that needs to be be done" - wording

"The combination of aggregated logs and a unifying identifiers" - wording

"that will allow us to choose between **a**" - replace "a" with "an"

"All of them can be **use** with Spring Boot" - used

"can connect to the docker.sock and **receives** all" - receive

"messages being generated by all of other containers" - wording

"containers can plug into,to capture" - wording/comma usage

"Now when we fire up our Docker environment in this chapter all" - consider comma after "chapter"

"This **features** allows you to do" - feature

"Do not underestimate **how it important it is**" - wording

"We found issue only after spending" - missing "an"

"language for querying the **consolidate** logs" - consolidated?

"annotations and Spring Cloud Sleuth **java**" - capitalize Java

"Spring **cloud sleuth** core has the Spring" - capitalize Cloud Sleuth

"method allows us to retrieve as a **string** the current" - capitalize String

"if we invoke **a** EagleEye" - an

"A clean concise picture can be worth than a million log entries" - wording

"breaks down the time spent of each microservice" - wording

"To use ZipKin you first" - capitalization, should be Zipkin?

"that simplifies the **using** of Zipkin" - use?

"At this point you, should be able to build, compile" - comma placement

"using the **In**-memory database in a production system" - capitalization

"The in-memory database **is can hold**" - wording

"Spring property on each of the service sending data to **Spring**." - did you mean Zipkin instead of Spring?

"Let’s start section with a scenario" - wording

"EagleEye application **in** running really slow" - is?

"Let’s begin, but by using to Zipkin by" - wording

"What we are going to do use POSTMAN" - wording

"Zipkin has captured for **traces** results" - trace

"Each of the transactions are broken down **in one more** spans" - one or more?

"It receives the incoming the HTTP call" - wording

"From figure 9.12 we can see **that entire** transaction" - missing "the"?

"One of the most **valuables** pieces of information" - valuable

"service involves 4 discrete HTTP **call**" - calls

"We see the call to **the** Zuul" - eliminate "the"

"produced and published via Spring **Cloud Bus**" - Did you mean Cloud Stream?

"demonstrated how to use the add the trace id" - wording

"what if we to perform traces out to third-party" - wording

"#A The Tracer class is used access" - wording

"name of the service that is going to capture." - wording

**Comment by carnellj** [comment]
Fixed
