### ISSUE TITLE
Listing 9.1 and 9.3

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#188]
John,

In listing 9.1, you show the following two dependencies:

```
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-sleuth</artifactId>    //#A
</dependency>   

<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-sleuth-core</artifactId>        //#B
</dependency>
```

The `spring-cloud-sleuth-core` dependency doesn't need to be specified because it is brought in as a dependency for `spring-cloud-starter-sleuth` automatically.

Looking at the code, we see that `spring-cloud-sleuth-core` was explicitly specified in the licensing service and the zuulsvr pom files, but not the organization service.

Fixing this would impact the paragraphs immediately before this code listing.  You can simply search for `spring-cloud-sleuth-core`.  This would also impact the code.

**Note, this also impacts Listing 9.3**

**Comment by carnellj** [comment]
Fixed.
