### ISSUE TITLE
Running the code examples

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#189]
John,

The code doesn't run without modification in this chapter.  I suspect its because Papertrail needs to be configured.  In the logs, the organization, licensing and zulu instances complain with the following log message:

`nc: getaddrinfo: Name does not resolve`

I will verify that this is the case.  The challenge here is that early in the chapter (See figure 9.1), you encourage the reader to test things out.  Can you consider adding a comment of some kind to indicate that Papertrail needs to be configured to get this to work?

**Comment by carnellj** [comment]
This is related to the postgres issue where the Postgres 9.6 came out and was incompatible with 9.5.  Delete your postgres database and this should be fine.  Papertail never has a direct dependency in the code.  What happens is the logstash Docker container is listening for logging messages being written to stdout.  Logstash then picks up messages and sends them to papertrail.  The beauty of this approach is none of the services need to know about log aggregation.  Its all handled seamlessly.

Assigning back to you, but if you agree then go ahead and just close the ticket.
