### ISSUE TITLE
Backing into your AWS region

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#200]
John,

I am not an expert AWS user.  For my information (and perhaps your readers), is this the only way to tell which region you are on:

http://docs.aws.amazon.com/general/latest/gr/rande.html

The console seems to give you only the region name.  For example, for me, it only shows "Oregon".  I had to use this page to back into the fact that "Oregon" is the "us-west-2" region.

Thoughts?

**Comment by carnellj** [comment]
Fixed
