### ISSUE TITLE
Chapter 10 Typos/Wording/Comma Usage

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#204]
Search for the following:

"We are the end of the book" - wording

"there should no human intervention" - missing "be"?

"devilish difficult bugs to track down - wording

"tenants of a microservice development" - consider removing "a"

"whose sole job it is to" - consider removing "it"

"implementing a build and deployment pipeline" - missing period

"we want all traffic for server" - wording

"Uncheck the two **checks** boxes" - "check"

"ECS offers a wizard for setting up **a** ECS" - "an"

"can only be accessed by other servers only if" - wording?

"demonstrate how to leverage **Cloudformation**" - "CloudFormation"

"we are going deploy the EagleEye" - wording

"deploying our services **if** fun" - "is"

"In the second part of this section" - wording

"really caps of the work" - wording

"that you want debug from the" - missing "to"

"repository for changes kicks off a build" - missing "and"

"application server running on, usually a development, server somewhere" - wording and/or comma usage

"In our build and deployment deployment " - duplicate words

"deploy officially new to a new environment" - wording?

"have been made seen the deployment of" - wording

"not only being built and test when it" - "tested"

"Once a server image is built the configuration" - comma after built?

"This is tremendous help in ensuring" - wording

"exposes situations where you have a state in" - consider removing "a"

"we are now going to **starting** walking" - wording, "start"?

"Figure 10.16 Technologies using in the thoughtmechanix build" - should this be: "Technologies used in the EagleEye build"?

"Docker **machine** image that will be deployed" - Is "machine" needed?

"I am firm believer in using" - wording, missing "a"?

"I think Python is fantastic programming language" - missing "a"?

"maven" - Do a find and replace and correct the case to "Maven".  This occurs many times.

"locally running Docker repo" - "repository"

"third-party libraries or command-lines that" - command-line tools?

"The first part of our Ttravis.yml" - .travis.yml

"java and jdk attributes as Java" - in this case, Java should be lowercase as it is in the code listing

"ensure that the JDK is installed configured" - missing "and"

"copies of Jar dependencies" - not sure if "Jar" should be capitalized or not.  "jar" is mentioned soon afterwards

"The next two attributes in the list 10.2 are" - wording

"ttribute and the services **attributes**" - attribute

"The **service** attribute is used to" - should be "services"

"attribute is used to Travis whether" - wording

"we need to Docker running" - wording

"to email and always notifying us" - wording

"Travis **Ci** can notify via multiple" - capitalization 

"email including via Slack" - consider removing "via"

"build off the **master** branch of Git" - code format "master"

"In our build process we communicate" - consider comma after process

"followed by a long **string** of text" - "String"

"Even though all our examples are" - wording, missing "of"?

"This is the command-line for" - command-line tool?

"#A Installs the travis command-line tool" - should Travis be capitalized here?

"Install the Amazon ECS client" - change to "Installs" to be consistent with bullets A-D

"starting and stopping **docker** containers " - "Docker"

"#C Using CURL tool to make invoke the service" - Should "curl" be in lowercase?

"executing the call via the **CURL** command" - should "curl" be in lowercase in formatted as code?

"unit and integration tests, and" - is comma necessary?

"At this point in the build the services have been compiled" - comma after build?

"The first thing we have to do is login **into**" - replace with "to"

"#C Using curl to invoke **the the**" - remove "the"

"code is the Travis CI command-line tool" - wording

"we are pass in two environment variables" - wording

"script is to invoke the **the**" - remove "the"

"done by using CURL to call" -  - should "curl" be in lowercase in formatted as code?  - "curl command"?

"n this repository are three Python scripts" - wording

"supported by DevOps team" - missing "the"?

**Comment by carnellj** [comment]
Fixed
