### ISSUE TITLE
Listing 2.3 - Need comment indicating body of class was removed

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#21]
In Listing 2.3, you may need a comment inserted into the class to let readers know that the body of the class was omitted.

Also... for cueball #2 - The code listing shows the following request mapping path:

`v1/organizations/{organizationId}/licenses`

The cue ball mentions the following path:

`/v1/organizations/{organizationId}/licenses`

Perhaps you can add a comment indicating that they are equivalent because Spring's DefaultAnnotationHandlerMapping class will add the leading slash if it is missing in the RequestMapping definition.

**Comment by carnellj** [comment]
Fixed
