### ISSUE TITLE
Missing Docker Images

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#212]
As part of the build process for Chapter 10, you have the user export and environment variable:

`export BUILD_NAME=”TestManualBuild”`

This gets used by each sub-project when tagging an image:

```
    <docker.image.name>johncarnell/tmx-eurekasvr</docker.image.name>
    <docker.image.tag>${env.BUILD_NAME}</docker.image.tag>
```

And referenced again in your docker-compose file:

`image:   johncarnell/tmx-eurekasvr:${BUILD_NAME}`

Right now, there aren't any images available with this tag though:

[https://hub.docker.com/r/johncarnell/tmx-eurekasvr/tags/](https://hub.docker.com/r/johncarnell/tmx-eurekasvr/tags/)

I am using eureka as an example, but it applies to all the images.  This is a problem if they are using your docker-compose file to run their containers on amazon as the images won't be sourced from their desktop.  They will be pulled from Docker Hub.

**Comment by carnellj** [comment]
Nothing to do
