### ISSUE TITLE
Fix Paths:

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#215]
chapter10-code/. travis.yml -> spmia-chapter10/.travis.yml

**Mentioned twice in section 1.6.4**
tag_build.sh -> travis_scripts/tag_build.sh

**Section 1.6.5**
chapter10-code/pom.xml -> spmia-chapter10/pom.xml

**Right before Listing 10.6**
deploy_to_docker_hub.sh -> travis_scripts/deploy_to_docker_hub.sh

**Comment by carnellj** [comment]
Fixed
