### ISSUE TITLE
Environment Variable Listing - CONTAINER_IP

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#219]
On page 31, you have the following:

```
BUILD_NAME
CONTAINER
PLATFORM_TEST_NAME
```

"CONTAINER" needs to change to "CONTAINER_IP"

Also, following this code listing, you show a code fragment form the .travis.yml file.  The value for the CONTAINER_IP is out of sync with the source.  It should be:  

`- export CONTAINER_IP=52.53.157.196`

**Comment by carnellj** [comment]
Fixed
