### ISSUE TITLE
@RestController annotation includes the @ResponseBody annotation

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#22]
Take or leave this one...

After listing 2.3, you talk about the @RestController annotation.  The last sentence in the paragraph says "This is all handled by the presence of the @RestController annotation".

It may be more clear if you mention that "This is all handled by the presence of the @RestController annotation which includes the @ResponseBody annotation"

**Comment by carnellj** [comment]
Fixed
