### ISSUE TITLE
Listing 2.4 - Using new Spring 4.3 Composed @RequestMapping Variants

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#24]
Spring 4.3 introduced a number of method level composed @RequestMapping Variants:

- `@GetMapping`
- `@PostMapping`
- `@PutMapping`
- `@DeleteMapping`
- `@PatchMapping`

These annotations simply make decorating methods more concise.  This allows you to collapse the RequestMapping annotation you have in Listing 2.4 from:

`@RequestMapping(value="/{licenseId}",method = RequestMethod.GET)`

To:

`@GetMapping("/licenseId")`

These annotations can be used throughout your book and code.

**Comment by carnellj** [comment]
Fixed
