### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#25]
John,

Is the README.md file for chapter 2 out of date?  Is it still necessary to use:

`docker-machine ip`

If not, can we update the text and perhaps change the address used to call the service to localhost?

Also, the directions for running the application are wrong.  Unless you align the directory structure of chapters 1 & 2 to be like the rest of the book, the command should be:

`docker-compose -f docker-compose/common/docker-compose.yml up`

**Note:**  For every other chapter, the command would be:

`docker-compose -f docker/common/docker-compose.yml up`

**Comment by carnellj** [comment]
Hey Josh.   I went through all the chapters and added readme files to all chapters.  I am directing the users to the Appendix for detailed setup and then also removed all docker machine references. 

     Thanks,
         John
