### ISSUE TITLE
Consider adding the "insecure" flag to your curl command

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#26]
In your Dockerfile, please consider changing this:
`curl -LO "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"`

to this:
`curl -kLO "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"`

The extra "-k" switch on curl allows it to make "insecure" connections.  This usually comes up when users are behind a corporate web gateway where they rewrite certificates.  While their local machine may be configured to handle the certs correctly, it won't within the docker image we are using causing curl to fail.

This would apply to the following files:

- carnellj/spmia-chapter3/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter4/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter5/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter6/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter7/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter8/confsvr/src/main/docker/Dockerfile
- carnellj/spmia-chapter10/confsvr/src/main/docker/Dockerfile

**Comment by carnellj** [comment]
Done

**Comment by joshuawhite929** [comment]
Found another one... The JWT_Example branch of Chapter 7

**Comment by carnellj** [comment]
Fixed
