### ISSUE TITLE
Wrong figure reference in text

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#29]
The paragraph right above figure 3.2 makes reference to figure 3.3.  I suspect that you meant 3.2.

I am confused now...  right before you list the source for the licensingservice.yml file, you refer to the figure as 3.3 again.  Did you remove a figure or renumber them?  If not, this reference may need to change to 3.2 as well.

**Comment by carnellj** [comment]
I think the copy editors, myself or marina fixed this as I do not see the issue.  I might have fixed it to when I had to go through and export the graphics
