### ISSUE TITLE
Figure 3.2 - /licensingservice or /licensingservice/default

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#32]
John,

In this figure, you have three environments shown.  For the default environment, you have the path "/licensingservice".  If you were to call this service that way (http://localhost:8888/licensingservice), you would get a 404.  As you show later, you actually have to call http://localhost:8888/licensingservice**/default**.

With this in mind, do you feel its necessary to update the diagram to reflect this? (change /licensingservice to /licensingservice/default)

**Comment by carnellj** [comment]
Fixed
