### ISSUE TITLE
Figure 3.3 and Figure 3.4 - Shows Git configuration when you talking about filesystem configuration

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#33]
John,

I believe the output in Figure 3.3 and Figure 3.4 shows how this would look if you had GIT configured, not a file system.  You don't talk about using GIT to back the config server until later in the chapter.  Perhaps you meant to show a different output?

FYI - If users run the source code they downloaded from GIT, it would should this result as the source code reflects the GIT backed config server, not the filesystem backed config server.  You'll have to change the source locally to capture the right output for this listing

**Comment by carnellj** [comment]
fixed
