### ISSUE TITLE
Fix path in "Use environment variables to pass startup information" callout

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#38]
In this text, you show a path of `Docker/dev./docker-compose.yml`.  There are a couple of errors in it.  It should be `docker/dev/docker-compose.yml`

The source code that you are showing suffers from bad formatting (some of the source is in bold).  Also, it is out of sync with the source.  I believe you stopped using "links".  Also, the source of the run.sh file which is also partially shown is out of sync.

**Comment by carnellj** [comment]
fixed
