### ISSUE TITLE
Figure 3.9 - Does the user know what to start to run on port 8080?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#39]
John,

Right before Figure 3.9, you ask the user to hit http://localhost:8080/env.  At this point, I am not sure that the user knows what should be running to make this work.  Previously, they were running the config server on port 8888.  Its not clear that they need to start the license server to get something running on port 8080.

Also... there are some headaches with this.  Now that you have added encrypting properties in this chapter, this example doesn't run when the user pulls the source from git.  It fails with the exception:

java.lang.IllegalStateException: Cannot decrypt: key=spring.datasource.password

This is because you need to do some additional things to make the code work later in the chapter.  How do you want to handle this?

**Comment by carnellj** [comment]
Fixed by adding a note to tell them the services will not start locally if these properties are not set
