### ISSUE TITLE
Wrong datasource Url referenced from text?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#40]
John,

After figure 3.9, you mention the following url:

`jdbc:postgresql://database:5432/eagle_eye_dev`

Looking in the licensingservice-dev.yml file, shouldn't this be:

`jdbc:postgresql://192.168.99.100:5432/eagle_eye_dev`

Please validate

**Comment by carnellj** [comment]
Fixed
