### ISSUE TITLE
Encryption Key in text is wrong

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#48]
A couple of things here...

1.  Your docker-compose file uses the key ENCRYPT_KEY:       "IMSYMMETRIC"
2.  The text of the book (after section 3.4.2) lists "IAMSYMMETRIC".  Note that this is mentioned again later in the text as well.
3.  While this may work when you run docker, I don't think the reader knows what to do with this when running the example directly.  Is this something you should address in the chapters README file?
4.  When I run the example, I still get an error about having the wrong key either way.  Can you set the environment variable within your IDE and run the example without using docker to see if it works for you?

I suspect that the quotes are removed when the value is passed in from the docker-compose file.  From an environmental variable perspective, the value may be:

`export ENCRYPT_KEY=IMSYMMETRIC`

**Comment by carnellj** [comment]
fixed
