### ISSUE TITLE
encrypt/decrypt endpoints not working

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#49]
John,

I didn't spend much time debugging this as I am sure I am missing something.  Starting up the code base using docker-compose, both instances start on port 8080 and 8888.  Looking at the /env endpoint, I can see that both show that the ENCRYPT_KEY environment variable are there.  The problem is though, that I get a 404 at http://localhost:8888/encrypt

UPDATE:
I am embarrassed to tell you that I was using a GET instead of a POST.  With that in mind, I think we need to make that more clear in the text.

**Comment by carnellj** [comment]
Fixed
