### ISSUE TITLE
Figure 1.8 clarification - Where is the "DEV" environment?  Where does the use of containers & automated build process start?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#7]
In Figure 1.8, does "DEV" represent a developers local development environment (ex. their laptop) or a destination for code afterwards?  Based on this diagram, it feels like "DEV" might be something beyond the laptop based development environment.  Also, the text in the diagram seems to hint at things starting after developers check in their code.

Where I work, we call our laptop our "UNIT" environment and "DEV" is the first destination after this environment after "UNIT".  Perhaps you could clarify your intent as people may read this coming from different experiences.

**Comment by carnellj** [comment]
I changed the build and deployment pipeline diagram pretty significantly in the P3 edits.  Also I added a note in section 1.9.6 to clarify about where things run
