### ISSUE TITLE
Listing 4.9 - Extra annotations?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#76]
In listing 4.9 you have the following:

```
@EnableDiscoveryClient
@EnableFeignClients
```

I get it, you are working through the various service discovery clients.  Can you consider adding extra bullets to both Listing 4.9 and Listing 4.5.3 to indicate which annotations are need in which scenario?  For example, for the example in 4.9, you don't need both of these annotation.  I think if you can call it out and explain it, it will make it more clear to the reader.

Note, the same can be said for Listing 4.11

**Comment by carnellj** [comment]
Fixed.
