### ISSUE TITLE
Chapter 5 Typos and Wording

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#78]
Search for the following text:

"Demonstrating how to use Hystrix to fallback to **alternative to** code"

"When a service crashes it is easy to detect **that is** no longer there"

"out **and calling** client must wait"

(Figure 5.1) "The circuit **break** pattern"

(Missing comma) "rather than just generating an exception the service consumer"

(Figure 5.2) "Application and B use service A to do work"  should probably be "Application **A** and B use service A to do work"

(Figure 5.2) "Service A calls Service B to do some work" - this appears twice

"then **when service** started performing poorly"

"We are going to wrapper the getLicensesByOrg() **method on in our**"

"In the previous chapter**.** we gave an example" - period should be a comma

"The author **on one more then** occasion "

"Lets’ simulate the getLicensesByOrg()" - apostrophe placement

"length of the timeout (in milliseconds) **the circuit breaker**"

"we decided to protect the service call that retrieved and **summarize** the customer’s"

"The key when choosing whether to not to use a fallback **strategy the level of tolerance** your customers"

"I failed to take this into **account in his fallbacks**."

"performance problems with one service out of many can result in all of the **thread** for the Java container"

"dominating all of **threads the default** thread pool."

"objects that **can be used control** the behavior"

"**There** a couple of things to note about "

"Hystrix will allow another **call to through to see**"

"and the **more** number of buckets your keep within the window"

"This allows **you fine tune** your remote service" (Take a look at the wording of this entire sentence)

"Hystrix configuration can occur at three levels of granularity" - Is this sentence necessary?  Read the next sentence.

"The class-level properties **are set class level annotation** called"

"10 seconds you **could set use the**"

"all Thread pools **that** will inherit either"

"The Hystrix threadPoolProperties and commandProperties defined with that command key." - Wording???

"catch the thrown exception and do any resource clean up or **clean** error handling"

"contextual information in a **custom your code**"

"**request will to the** UserContext object"

"check whether to call the existing concurrency strategy’s is present " - Wording?

"existing concurrency strategy or the base Hystrix concurrency strategy call" - Wording?

"Otherwise, we can have some nasty behavior when trying to **implement leverage**"

"LicenseService.getLicenseByOrg Correlation: TEST-CORRELATIOn-ID" - Notice case of "n" in "TEST-CORRELATIOn-ID"

"its failures should be allowed to eat up" - probably should be "shouldn't be"

"completely isolates a Hystrix protected **all**, " - probably should be "call"

"**Hystrix’s** does allow you to inject the parent"

**Comment by carnellj** [comment]
Fixed.
