### ISSUE TITLE
Figure 5.3 - Should the names of the micro services be changing?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#80]
Looking at figure 5.3, are we trying to emphasize 3 different scenarios for a given service here?

For example, instead of having "Microservice A", "Microservice B" and "Microservice C", are we really talking about 3 different situations and how hystrix is used for each?

If so, can you consider using vertical swim lanes and/or naming each of the scenarios according to the text?

**Comment by carnellj** [comment]
Done
