### ISSUE TITLE
Redundant dependency specified

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#82]
Right after section 5.4, you show the following:

```
<dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-hystrix</artifactId> 
</dependency> 

<dependency>
  <groupId>com.netflix.hystrix</groupId>       
  <artifactId>hystrix-core</artifactId>
  <version>1.5.9</version>
</dependency>
```

`spring-cloud-starter-hystrix` already includes `hystrix-core` as a dependency (version 1.5.6).  As a result, this extra dependency isn't necessary.  This would impact both the code and the text, potentially in multiple chapters.

**Comment by carnellj** [comment]
Couple of things:

1.  The text was wrong.  it should have been hystrix-javanica not hystrix-core.  The code was right the text was wrong.
2.  I purposely upgraded to a later version of javanica.  The default version pulled in by Camden.SR5 (hystrix-javanica 1.5.6) changed the behavior of how fallback were handled then previous version of javanica.  Hystrix previously always threw a HystrixRuntimeException when a call timed out, but hand no fallback.  In 1.5.6, they threw a UndeclaredThrowableException.  In the latest version of hystrix they moved back to a HystrixRuntimeException.  So I overrode the version of hystrix used by Spring Cloud to move us back to "normal" behavior.  I added a note in the text about why I overrode the javanica librabries.
