### ISSUE TITLE
Wrong address used for licensing service

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#86]
In the text you use the following URL:

`http://192.168.99.100:8080/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/ `

The URL should be:

`http://localhost:8080/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/`

**Comment by carnellj** [comment]
Fixed
