### ISSUE TITLE
Can't find the code thats listed in the beginning of Section 5.5.1

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#87]
FYI - I can't seem to find this code in the source:

```
@HystrixCommand
private Organization getOrganization(String organizationId) {
 return organizationRestClient.getOrganization(organizationId);
}
```

The closest that I have found is the OrganizationRestTemplateClient class.  As a result, I have not verified that this listing aligns with the source code.

**Comment by carnellj** [comment]
Its there.  Its in the LicenseService call.  Lines 47-50.  Its actually invoked in line 37
