### ISSUE TITLE
Listing 5.4 and Figure 5.6

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#89]
In its current state, the code in Listing 5.4 is commented out in the source.  If and when the user tries to run this code (assuming that it is set up to work), they won't be able to validate the behavior seen in Figure 5.6.

To make this more intuitive to the end user, can you let the reader know that they will need to uncomment out code to see the behavior after validating the behavior shown in Figure 5.5 (where hystrix simply fails and creates a 500 error).

**Comment by carnellj** [comment]
Done
