### ISSUE TITLE
Source code for listing 1.2?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#9]
John,

This seems like an enhanced version of the code from listing 1.1.  Because it has the same name (com.thoughtmechanix.simpleservice.Application), how did you want to represent this within Git?  As far as I can tell, the code from listing 1.1 isn't in Git today.

**Comment by carnellj** [comment]
Hey Josh,

It was only meant as example and so it is not in GIT.  Do you think I should add a note to the chapter.  I really did not include an example because I would have had to pull in the world.
