### ISSUE TITLE
Externalizing Hystrix config?

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#91]
John,

Search for the following text:

"Note: The author personally does not like to set global property values"

I am confused by the first two paragraphs on this page.  In the first paragraph, you don't like to set values in the Hystrix annotations... but in the very next paragraph you say that you want to keep the configuration as close to the code as possible.

It could be me, but I had a difficult time rationalizing these two paragraphs.  Also, when I think about embedding this configuration into the annotations, I think about how you would need to rebuild the application to make changes.  That is reason enough for me to try an externalize them.  Thoughts?

**Comment by carnellj** [comment]
Yeah that paragraph did not make sense.  I reworked it.
