### ISSUE TITLE
Chapter 6 Typos and Wording Problems

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#95]
Have the editors one through this???

Search for the following text:

"Setting **up a using** Spring Cloud"

"To implement this functionality  you will want these" - comma needed

"A service gateway all service calls"

"A services gateway can be used to **collection** metrics"

"discovery engine other then **Eureak**"

"communicate with the downstream clients Zuul" - needs comma

"running through your Zuul service **gatewy**"

"side car"  All instances should be sidecar

"you to change the mapping of route"

"github" should be "GitHub"

"that will cause to reload its route configuration" - missing "it"

"return an HTTP 500 error for any that call takes longer " - two items here...

"Zuul allows you to build custom logic by through"

"a gatekeeper to ensure that the user calling the service has authenticated"   - is it "has" or "is"?

"A post filter is invoked after target service"

"by Zuul as a request enters **the** Zuul"

"can inspect and modify **an** HTTP request "

"However, **A** Zuul Route filter does" - lowercase

"Zuul filters allows use to enforce"

"request flowing from Zuul has a correlation ID associated with"

"can be used to track a user’s request across multiple headers" - Did you mean microservices?

"on how to use Zuul to generate correlation-id"

"ThreadLocal" - Do you really mean "ThreadLocal variables"?

"that has serveral additional **methods in for accessing** Zulu-Specific values"

"A RestTemplate **is used invoke** the organization service"

"Our first class we are going to **build in the** "

"//Remove the imports for **consciness**"

"The reason, I took a share-nothing" - Is this comma needed?

"java" - should be "Java"

"from all of our services in single point" - into a single point?

"HTTP response headers being passed **back to caller of** the service"

"begins in the run() **method the code**"

"we are copying all of the values **from incoming** HTTP request"

"Zuul use the HTTP request"

"response **back the calling** service client"

"The alternative organization service **route return from** the special routes "

"you are able to easily add intelligence to your **services are routed**"

"retrieves the service ID for the **service is being called**"

**Comment by carnellj** [comment]
Done
