### ISSUE TITLE
Path is incorrect - zuulsvr/src/main/com/thoughtmechanix/zuulsvr/Application.java 

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#96]
Search for the following:

`zuulsvr/src/main/com/thoughtmechanix/zuulsvr/Application.java` 

this should be:

`zuulsvr/src/main/java/com/thoughtmechanix/zuulsvr/Application.java `

**Comment by carnellj** [comment]
Done
