### ISSUE TITLE
Wrong URL specified

### ISSUE THREAD

**Issue by joshuawhite929** [joshuawhite929/spmia_feedback#99]
In the text, you have the following URL:

`http://192.168.99.100:5555/organizationservice/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a`

It probably should be this (below) based on where we are in the text:

`http://localhost:5555/organizationservice/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a`

If the user wants to try it themselves though, the source currently expects this:

`http://localhost:5555/api/organization/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a`

**Comment by carnellj** [comment]
Fixed
